Check it out
ReginaValetova/Time_is_running_out pull request #3
Opened 2019-02-24 23:30 UTC by ReginaValetova

Диар Иван, мне нужно снова вас побеспокоить 
Теперь у меня такая же проблема с высотой колонок 
Я им указала "grid-template-rows: 40px 1fr;", но они даже не шелохнулись 
Вся надежда только на вас

2019-02-24 23:40 UTC, Betra commented on style.css
> +    grid-template-rows: 40px 1fr;
Если речь идет о том, чтобы сделать ряд на 40 пикселей и остальное, лучше `1fr` заменить на `auto`

2019-02-24 23:42 UTC, divanc requested changes

2019-02-24 23:42 UTC, Betra commented on style.css
>      grid-area: aside;
Не очень понял, почему снова и area и сетка

2019-02-24 23:45 UTC, ReginaValetova commented on style.css
>      grid-area: aside;
Я пока её не удалила
Что, по-твоему, лучше оставить?

2019-02-24 23:46 UTC, ReginaValetova commented on style.css
> +    grid-template-rows: 40px 1fr;
А почему 1fr не работает?

2019-02-24 23:49 UTC, Betra commented on style.css
>      grid-area: aside;
area халява, начни с сетки пока

2019-02-24 23:56 UTC, Betra commented on style.css
> +    grid-template-rows: 40px 1fr;
Вполне работает, можешь и оставить

2019-02-25 00:28 UTC, divanc approved these changes
Еще бы комментарии удалить, вообще супер, пока разбираешься, если хочешь, можешь приклеить в мастер

2019-02-26 22:47 UTC, merged